const List = require('../specification/daggy/List');

const ONE_EL_ARRAY = [ 123 ];

const TWO_ELS_ARRAY = [ 123, 11 ];
const TWO_ELS_ARRAY_SORTED = [ 11, 123 ];

const FIVE_ELS_ARRAY = [ 4, 12, 10, 10500, 6 ];
const FIVE_ELS_ARRAY_SORTED = [ 4, 6, 10, 12, 10500 ];

const TEN_ELS_ARRAY = [ 4, 12, 10, 10500, 6, 890, 1234, 243, 16, 846 ];
const TEN_ELS_ARRAY_SORTED = [ 4, 6, 10, 12, 16, 243, 846, 890, 1234, 10500 ];

const WORST_CASE_SCENARIO = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 0 ];
const WORST_CASE_SCENARIO_SORTED = [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ];

const EMPTY_LIST = List.from([]);
const ONE_EL_LIST = List.from(ONE_EL_ARRAY);

const TWO_ELS_LIST = List.from(TWO_ELS_ARRAY);
const TWO_ELS_LIST_SORTED = List.from(TWO_ELS_ARRAY_SORTED);

const FIVE_ELS_LIST = List.from(FIVE_ELS_ARRAY);
const FIVE_ELS_LIST_SORTED = List.from(FIVE_ELS_ARRAY_SORTED);

const TEN_ELS_LIST = List.from(TEN_ELS_ARRAY);
const TEN_ELS_LIST_SORTED = List.from(TEN_ELS_ARRAY_SORTED);

const WORST_CASE_SCENARIO_LIST = List.from(WORST_CASE_SCENARIO);
const WORST_CASE_SCENARIO_LIST_SORTED = List.from(WORST_CASE_SCENARIO_SORTED);

module.exports = {
  EMPTY_LIST,
  FIVE_ELS_ARRAY,
  FIVE_ELS_ARRAY_SORTED,
  FIVE_ELS_LIST,
  FIVE_ELS_LIST_SORTED,
  ONE_EL_ARRAY,
  ONE_EL_LIST,
  TEN_ELS_ARRAY,
  TEN_ELS_ARRAY_SORTED,
  TEN_ELS_LIST,
  TEN_ELS_LIST_SORTED,
  TWO_ELS_ARRAY,
  TWO_ELS_ARRAY_SORTED,
  TWO_ELS_LIST,
  TWO_ELS_LIST_SORTED,
  WORST_CASE_SCENARIO,
  WORST_CASE_SCENARIO_LIST,
  WORST_CASE_SCENARIO_LIST_SORTED,
  WORST_CASE_SCENARIO_SORTED
};
